### ISSUE TITLE
Требую какать

### ISSUE THREAD

**Issue by Kokosik428** [Villygrimm/KWM_BROWSER#1]
Я требую чтобы лаунчере была вожможность какать на видеокарту!

**Comment by Villygrimm** [comment]
ты шо тупой

**Comment by Kokosik428** [comment]
Ты в зеркало посмотрел?

**Comment by Kokosik428** [comment]
### _**ХОЧУ КАКАТЬ, ЖЁСТКО И СЛАДКО НА ШЕДЕВРОВИДЕОКАРТУ**_

**Comment by Villygrimm** [comment]
хватит срать
